app/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('Route');

Router::extensions(['html', 'rss','json','xml','xlsx', 'pdf']);
// Router::parseExtensions('pdf');


Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Mensajes', 'action' => 'index', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->connect('/webroot/facturas/*', ['controller' => 'Facturas']);
    $routes->connect(
        '/cotizacion/pdf/:id',
        ['controller' => 'Cotizaciones', 'action' => 'pdf'],
        ['id' => '\d+', 'pass' => ['id']]
    );

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `InflectedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'InflectedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'InflectedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('InflectedRoute');
});

Router::scope(
    '/bookmarks',
    ['controller' => 'Bookmarks'],
    function ($routes) {
        $routes->connect('/tagged/*', ['action' => 'tags']);
    }
);

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

app/src/Model/Table/CotizacionesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Cotizaciones Model
 *
 * @property \App\Model\Table\CentrosTable|\Cake\ORM\Association\BelongsTo $Centros
 * @property \App\Model\Table\UsuariosTable|\Cake\ORM\Association\BelongsTo $Usuarios
 * @property \App\Model\Table\MonedasTable|\Cake\ORM\Association\BelongsTo $Monedas
 * @property \App\Model\Table\OficinasTable|\Cake\ORM\Association\BelongsToMany $Oficinas
 *
 * @method \App\Model\Entity\Cotizacion get($primaryKey, $options = [])
 * @method \App\Model\Entity\Cotizacion newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Cotizacion[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Cotizacion|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Cotizacion patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Cotizacion[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Cotizacion findOrCreate($search, callable $callback = null, $options = [])
 */
class CotizacionesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('cotizaciones');
        $this->setDisplayField('cliente');
        $this->setPrimaryKey('id');
        $this->belongsTo('Centros', [
            'foreignKey' => 'centro_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Monedas', [
            'foreignKey' => 'moneda_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Usuarios', [
            'foreignKey' => 'usuario_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsToMany('Oficinas', [
            'foreignKey' => 'cotizacion_id',
            'targetForeignKey' => 'oficina_id',
            'joinTable' => 'cotizaciones_oficinas'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('cliente')
            ->requirePresence('cliente', 'create')
            ->notEmpty('cliente');

        $validator
            ->scalar('contacto')
            ->requirePresence('contacto', 'create')
            ->notEmpty('contacto');

        $validator
            ->scalar('correo')
            ->allowEmpty('correo');

        $validator
            ->scalar('telefono')
            ->allowEmpty('telefono');

        $validator
            ->scalar('telefono_movil')
            ->allowEmpty('telefono_movil');

        $validator
            ->integer('vigencia')
            ->requirePresence('vigencia', 'create')
            ->notEmpty('vigencia');

        $validator
            ->dateTime('vence')
            ->requirePresence('vence', 'create')
            ->notEmpty('vence');

        $validator
            ->integer('moneda_id')
            ->requirePresence('moneda_id', 'create')
            ->notEmpty('moneda_id');

        $validator
            ->scalar('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        $validator
            ->scalar('comentario')
            ->allowEmpty('comentario');

        $validator
            ->decimal('tipo_cambio')
            ->requirePresence('tipo_cambio', 'create')
            ->notEmpty('tipo_cambio');

        $validator
            ->boolean('aplica_promocion')
            ->requirePresence('aplica_promocion', 'create')
            ->notEmpty('aplica_promocion');

        $validator
            ->scalar('texto_inicial')
            ->allowEmpty('texto_inicial');

        $validator
            ->scalar('texto_final')
            ->allowEmpty('texto_final');

        $validator
            ->boolean('layout_centro')
            ->requirePresence('layout_centro', 'create')
            ->notEmpty('layout_centro');

        $validator
            ->dateTime('creada')
            ->requirePresence('creada', 'create')
            ->notEmpty('creada');

        $validator
            ->boolean('eliminado')
            ->requirePresence('eliminado', 'create')
            ->notEmpty('eliminado');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['centro_id'], 'Centros'));
        $rules->add($rules->existsIn(['usuario_id'], 'Usuarios'));
        $rules->add($rules->existsIn(['moneda_id'], 'Monedas'));

        return $rules;
    }
}

app/src/Template/Cotizaciones/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Cotizacion $cotizacion
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $cotizacion->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $cotizacion->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Cotizaciones'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Oficinas'), ['controller' => 'Oficinas', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Oficina'), ['controller' => 'Oficinas', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Centros'), ['controller' => 'Centros', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Centro'), ['controller' => 'Centros', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Usuarios'), ['controller' => 'Usuarios', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Usuario'), ['controller' => 'Usuarios', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="cotizaciones form large-9 medium-8 columns content">
    <?= $this->Form->create($cotizacion) ?>
    <fieldset>
        <legend><?= __('Edit Cotizacion') ?></legend>
        <?php
            echo $this->Form->control('cliente');
            echo $this->Form->control('contacto');
            echo $this->Form->control('centro_id', ['options' => $centros]);
            echo $this->Form->control('correo');
            echo $this->Form->control('telefono');
            echo $this->Form->control('telefono_movil');
            echo $this->Form->control('vigencia');
            echo $this->Form->control('vence');
            echo $this->Form->control('moneda');
            echo $this->Form->control('status');
            echo $this->Form->control('usuario_id', ['options' => $usuarios]);
            echo $this->Form->control('tipo_cambio');
            echo $this->Form->control('aplica_promocion');
            echo $this->Form->control('texto_inicial');
            echo $this->Form->control('texto_final');
            echo $this->Form->control('layout_centro');
            echo $this->Form->control('creada');
            echo $this->Form->control('eliminado');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

app/src/Template/Cotizaciones/index.ctp
<?php
$this->extend('../Layout/TwitterBootstrap/dashboard');
?>
<?php echo $this->element('all_cotizaciones');?>

app/src/Template/Cotizaciones/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Cotizacion $cotizacion
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Cotizacion'), ['action' => 'edit', $cotizacion->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Cotizacion'), ['action' => 'delete', $cotizacion->id], ['confirm' => __('Are you sure you want to delete # {0}?', $cotizacion->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Cotizaciones'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Cotizacion'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Oficinas'), ['controller' => 'Oficinas', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Oficina'), ['controller' => 'Oficinas', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Centros'), ['controller' => 'Centros', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Centro'), ['controller' => 'Centros', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Usuarios'), ['controller' => 'Usuarios', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Usuario'), ['controller' => 'Usuarios', 'action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="cotizaciones view large-9 medium-8 columns content">
    <h3><?= h($cotizacion->cliente) ?></h3>
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('Cliente') ?></th>
            <td><?= h($cotizacion->cliente) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Contacto') ?></th>
            <td><?= h($cotizacion->contacto) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Centro') ?></th>
            <td><?= $cotizacion->has('centro') ? $this->Html->link($cotizacion->centro->nombre, ['controller' => 'Centros', 'action' => 'view', $cotizacion->centro->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Correo') ?></th>
            <td><?= h($cotizacion->correo) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Telefono') ?></th>
            <td><?= h($cotizacion->telefono) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Telefono Movil') ?></th>
            <td><?= h($cotizacion->telefono_movil) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Moneda') ?></th>
            <td><?= h($cotizacion->moneda) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Status') ?></th>
            <td><?= h($cotizacion->status) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Usuario') ?></th>
            <td><?= $cotizacion->has('usuario') ? $this->Html->link($cotizacion->usuario->username, ['controller' => 'Usuarios', 'action' => 'view', $cotizacion->usuario->id]) : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($cotizacion->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Vigencia') ?></th>
            <td><?= $this->Number->format($cotizacion->vigencia) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Tipo Cambio') ?></th>
            <td><?= $this->Number->format($cotizacion->tipo_cambio) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Vence') ?></th>
            <td><?= h($cotizacion->vence) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Creada') ?></th>
            <td><?= h($cotizacion->creada) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Aplica Promocion') ?></th>
            <td><?= $cotizacion->aplica_promocion ? __('Yes') : __('No'); ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Layout Centro') ?></th>
            <td><?= $cotizacion->layout_centro ? __('Yes') : __('No'); ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Eliminado') ?></th>
            <td><?= $cotizacion->eliminado ? __('Yes') : __('No'); ?></td>
        </tr>
    </table>
    <div class="row">
        <h4><?= __('Texto Inicial') ?></h4>
        <?= $this->Text->autoParagraph(h($cotizacion->texto_inicial)); ?>
    </div>
    <div class="row">
        <h4><?= __('Texto Final') ?></h4>
        <?= $this->Text->autoParagraph(h($cotizacion->texto_final)); ?>
    </div>
</div>